// Master-Datenbank für den PC-Konfigurator mit UVP (in CHF)
const cpus = [
    // =========================================================================
    // 1. AMD SOCKEL AM5 (Aktuelle Top-Gaming-Plattform – Nur DDR5)
    // =========================================================================
    // Ryzen 9000er Serie (Neueste Generation & X3D Gaming-Könige)
    {name: "AMD Ryzen 9 9950x3d2 (Dual Edition)", socket: "AM5", ram: "DDR5", rating: "97 (A+)", cinebench24single: "141", cinebench24multi: "2529", cores: "16 (16P)", tdpnormal: "200W", tdpboost: "270W", L3cache: "192MB", price: "749.-"},
    {name: "AMD Ryzen 9 9950X3D", socket: "AM5", ram: "DDR5", rating: "94 (A+)", cinebench24single: "138", cinebench24multi: "2456", cores: "16 (16P)", tdpnormal: "170W", tdpboost: "230W", L3cache: "128MB", price: "629.-"},
    {name: "AMD Ryzen 9 9950X", socket: "AM5", ram: "DDR5", rating: "93 (A+)", cinebench24single: "136", cinebench24multi: "2410", cores: "16 (16P)", tdpnormal: "170W", tdpboost: "230W", L3cache: "64MB", price: "579.-"},
    {name: "AMD Ryzen 9 9900X", socket: "AM5", ram: "DDR5", rating: "89 (A)", cinebench24single: "134", cinebench24multi: "1980", cores: "12 (12P)", tdpnormal: "120W", tdpboost: "162W", L3cache: "64MB", price: "449.-"},
    {name: "AMD Ryzen 7 9850X3D", socket: "AM5", ram: "DDR5", rating: "94 (A+)", cinebench24single: "137", cinebench24multi: "1590", cores: "8 (8P)", tdpnormal: "120W", tdpboost: "162W", L3cache: "96MB", price: "499.-"},
    {name: "AMD Ryzen 7 9800X3D", socket: "AM5", ram: "DDR5", rating: "92 (A+)", cinebench24single: "135", cinebench24multi: "1540", cores: "8 (8P)", tdpnormal: "120W", tdpboost: "162W", L3cache: "96MB", price: "459.-"},
    {name: "AMD Ryzen 7 9700X", socket: "AM5", ram: "DDR5", rating: "83 (B)", cinebench24single: "130", cinebench24multi: "1240", cores: "8 (8P)", tdpnormal: "65W", tdpboost: "105W", L3cache: "32MB", price: "349.-"},
    {name: "AMD Ryzen 5 9600X", socket: "AM5", ram: "DDR5", rating: "75 (C)", cinebench24single: "126", cinebench24multi: "1020", cores: "6 (6P)", tdpnormal: "65W", tdpboost: "105W", L3cache: "32MB", price: "269.-"},
    
    // Ryzen 7000er Serie (Preiskracher für Gaming)
    {name: "AMD Ryzen 9 7950X3D", socket: "AM5", ram: "DDR5", rating: "88 (A)", cinebench24single: "122", cinebench24multi: "2200", cores: "16 (16P)", tdpnormal: "120W", tdpboost: "162W", L3cache: "128MB", price: "649.-"},
    {name: "AMD Ryzen 9 7900X3D", socket: "AM5", ram: "DDR5", rating: "82 (B)", cinebench24single: "118", cinebench24multi: "1650", cores: "12 (12P)", tdpnormal: "120W", tdpboost: "162W", L3cache: "128MB", price: "529.-"},
    {name: "AMD Ryzen 7 7800X3D", socket: "AM5", ram: "DDR5", rating: "82 (B)", cinebench24single: "115", cinebench24multi: "1110", cores: "8 (8P)", tdpnormal: "120W", tdpboost: "162W", L3cache: "96MB", price: "419.-"},
    {name: "AMD Ryzen 7 7700X", socket: "AM5", ram: "DDR5", rating: "76 (C)", cinebench24single: "117", cinebench24multi: "1160", cores: "8 (8P)", tdpnormal: "105W", tdpboost: "142W", L3cache: "32MB", price: "379.-"},
    {name: "AMD Ryzen 5 7600X", socket: "AM5", ram: "DDR5", rating: "66 (C)", cinebench24single: "114", cinebench24multi: "890", cores: "6 (6P)", tdpnormal: "105W", tdpboost: "142W", L3cache: "32MB", price: "249.-"},
    {name: "AMD Ryzen 5 7600", socket: "AM5", ram: "DDR5", rating: "63 (D)", cinebench24single: "110", cinebench24multi: "840", cores: "6 (6P)", tdpnormal: "65W", tdpboost: "88W", L3cache: "32MB", price: "209.-"},
    {name: "AMD Ryzen 5 7500F", socket: "AM5", ram: "DDR5", rating: "60 (D)", cinebench24single: "106", cinebench24multi: "810", cores: "6 (6P)", tdpnormal: "65W", tdpboost: "88W", L3cache: "32MB", price: "169.-"},

    // =========================================================================
    // 2. INTEL SOCKEL LGA1851 (Core Ultra Generation – Nur DDR5)
    // =========================================================================
    {name: "Intel Core Ultra 9 285K", socket: "1851", ram: "DDR5", rating: "96 (A+)", cinebench24single: "142", cinebench24multi: "2510", cores: "24 (8+16E)", tdpnormal: "125W", tdpboost: "250W", L3cache: "36MB", price: "569.-"},
    {name: "Intel Core Ultra 7 270K Plus", socket: "1851", ram: "DDR5", rating: "98 (A+)", cinebench24single: "145", cinebench24multi: "2482", cores: "24 (8+16E)", tdpnormal: "125W", tdpboost: "250W", L3cache: "36MB", price: "449.-"},
    {name: "Intel Core Ultra 7 265K", socket: "1851", ram: "DDR5", rating: "88 (A)", cinebench24single: "135", cinebench24multi: "2070", cores: "20 (8+12E)", tdpnormal: "125W", tdpboost: "250W", L3cache: "30MB", price: "389.-"},
    {name: "Intel Core Ultra 7 265KF", socket: "1851", ram: "DDR5", rating: "88 (A)", cinebench24single: "135", cinebench24multi: "2070", cores: "20 (8+12E)", tdpnormal: "125W", tdpboost: "250W", L3cache: "30MB", price: "369.-"},
    {name: "Intel Core Ultra 5 245K", socket: "1851", ram: "DDR5", rating: "79 (B)", cinebench24single: "122", cinebench24multi: "1460", cores: "14 (6+8E)", tdpnormal: "125W", tdpboost: "159W", L3cache: "24MB", price: "299.-"},
    {name: "Intel Core Ultra 5 245KF", socket: "1851", ram: "DDR5", rating: "79 (B)", cinebench24single: "122", cinebench24multi: "1460", cores: "14 (6+8E)", tdpnormal: "125W", tdpboost: "159W", L3cache: "24MB", price: "279.-"},

    // =========================================================================
    // 3. INTEL SOCKEL LGA1700 (12./13./14. Generation – Unterstützt DDR4 oder DDR5)
    // =========================================================================
    // Core i9 (Brutale Leistung)
    {name: "Intel Core i9-14900K", socket: "LGA1700", ram: "DDR4/DDR5", rating: "91 (A)", cinebench24single: "132", cinebench24multi: "2340", cores: "24 (8+16E)", tdpnormal: "125W", tdpboost: "253W", L3cache: "36MB", price: "549.-"},
    {name: "Intel Core i9-14900KF", socket: "LGA1700", ram: "DDR4/DDR5", rating: "91 (A)", cinebench24single: "132", cinebench24multi: "2340", cores: "24 (8+16E)", tdpnormal: "125W", tdpboost: "253W", L3cache: "36MB", price: "519.-"},
    {name: "Intel Core i9-13900K", socket: "LGA1700", ram: "DDR4/DDR5", rating: "89 (A)", cinebench24single: "128", cinebench24multi: "2210", cores: "24 (8+16E)", tdpnormal: "125W", tdpboost: "253W", L3cache: "36MB", price: "529.-"},
    {name: "Intel Core i9-13900KF", socket: "LGA1700", ram: "DDR4/DDR5", rating: "89 (A)", cinebench24single: "128", cinebench24multi: "2210", cores: "24 (8+16E)", tdpnormal: "125W", tdpboost: "499.-"},
    {name: "Intel Core i9-12900K", socket: "LGA1700", ram: "DDR4/DDR5", rating: "78 (B)", cinebench24single: "115", cinebench24multi: "1590", cores: "16 (8+8E)", tdpnormal: "125W", tdpboost: "241W", L3cache: "30MB", price: "399.-"},

    // Core i7 (Gehobene Gaming-Klasse)
    {name: "Intel Core i7-14700K", socket: "LGA1700", ram: "DDR4/DDR5", rating: "86 (B)", cinebench24single: "128", cinebench24multi: "2080", cores: "20 (8+12E)", tdpnormal: "125W", tdpboost: "253W", L3cache: "33MB", price: "399.-"},
    {name: "Intel Core i7-14700KF", socket: "LGA1700", ram: "DDR4/DDR5", rating: "86 (B)", cinebench24single: "128", cinebench24multi: "2080", cores: "20 (8+12E)", tdpnormal: "125W", tdpboost: "253W", L3cache: "379.-"},
    {name: "Intel Core i7-13700K", socket: "LGA1700", ram: "DDR4/DDR5", rating: "81 (B)", cinebench24single: "124", cinebench24multi: "1890", cores: "16 (8+8E)", tdpnormal: "125W", tdpboost: "253W", L3cache: "30MB", price: "389.-"},
    {name: "Intel Core i7-13700KF", socket: "LGA1700", ram: "DDR4/DDR5", rating: "81 (B)", cinebench24single: "124", cinebench24multi: "1890", cores: "16 (8+8E)", tdpnormal: "125W", tdpboost: "253W", L3cache: "30MB", price: "359.-"},
    {name: "Intel Core i7-12700K", socket: "LGA1700", ram: "DDR4/DDR5", rating: "72 (C)", cinebench24single: "112", cinebench24multi: "1310", cores: "12 (8+4E)", tdpnormal: "125W", tdpboost: "190W", L3cache: "25MB", price: "289.-"},

    // Core i5 (Absoluter Gaming-Mainstream)
    {name: "Intel Core i5-14600K", socket: "LGA1700", ram: "DDR4/DDR5", rating: "78 (B)", cinebench24single: "120", cinebench24multi: "1420", cores: "14 (6+8E)", tdpnormal: "125W", tdpboost: "181W", L3cache: "24MB", price: "299.-"},
    {name: "Intel Core i5-14600KF", socket: "LGA1700", ram: "DDR4/DDR5", rating: "78 (B)", cinebench24single: "120", cinebench24multi: "1420", cores: "14 (6+8E)", tdpnormal: "125W", tdpboost: "181W", L3cache: "24MB", price: "279.-"},
    {name: "Intel Core i5-13600K", socket: "LGA1700", ram: "DDR4/DDR5", rating: "74 (C)", cinebench24single: "117", cinebench24multi: "1380", cores: "14 (6+8E)", tdpnormal: "125W", tdpboost: "181W", L3cache: "24MB", price: "289.-"},
    {name: "Intel Core i5-13600KF", socket: "LGA1700", ram: "DDR4/DDR5", rating: "74 (C)", cinebench24single: "117", cinebench24multi: "1380", cores: "14 (6+8E)", tdpnormal: "125W", tdpboost: "181W", L3cache: "24MB", price: "269.-"},
    {name: "Intel Core i5-14400F", socket: "LGA1700", ram: "DDR4/DDR5", rating: "63 (D)", cinebench24single: "107", cinebench24multi: "1010", cores: "10 (6+4E)", tdpnormal: "65W", tdpboost: "148W", L3cache: "20MB", price: "209.-"},
    {name: "Intel Core i5-13400F", socket: "LGA1700", ram: "DDR4/DDR5", rating: "61 (D)", cinebench24single: "105", cinebench24multi: "980", cores: "10 (6+4E)", tdpnormal: "65W", tdpboost: "148W", L3cache: "20MB", price: "199.-"},
    {name: "Intel Core i5-12400F", socket: "LGA1700", ram: "DDR4/DDR5", rating: "54 (D)", cinebench24single: "100", cinebench24multi: "760", cores: "6 (6P)", tdpnormal: "65W", tdpboost: "117W", L3cache: "18MB", price: "129.-"},

    // Core i3 (Das absolute Minimum für Budget-FullHD)
    {name: "Intel Core i3-14100", socket: "LGA1700", ram: "DDR4/DDR5", rating: "48 (E)", cinebench24single: "102", cinebench24multi: "530", cores: "4 (4P)", tdpnormal: "60W", tdpboost: "110W", L3cache: "12MB", price: "119.-"},
    {name: "Intel Core i3-12100F", socket: "LGA1700", ram: "DDR4/DDR5", rating: "42 (E)", cinebench24single: "93", cinebench24multi: "490", cores: "4 (4P)", tdpnormal: "60W", tdpboost: "89W", L3cache: "12MB", price: "89.-"},

    // =========================================================================
    // 4. AMD SOCKEL AM4 (Die legendäre Sparfuchs-Gaming-Plattform – Nur DDR4)
    // =========================================================================
    {name: "AMD Ryzen 9 5950X", socket: "AM4", ram: "DDR4", rating: "79 (B)", cinebench24single: "101", cinebench24multi: "1510", cores: "16 (16P)", tdpnormal: "105W", tdpboost: "142W", L3cache: "64MB", price: "529.-"},
    {name: "AMD Ryzen 9 5900X", socket: "AM4", ram: "DDR4", rating: "71 (C)", cinebench24single: "100", cinebench24multi: "1220", cores: "12 (12P)", tdpnormal: "105W", tdpboost: "142W", L3cache: "64MB", price: "399.-"},
    {name: "AMD Ryzen 7 5800X3D", socket: "AM4", ram: "DDR4", rating: "68 (C)", cinebench24single: "98", cinebench24multi: "910", cores: "8 (8P)", tdpnormal: "105W", tdpboost: "142W", L3cache: "96MB", price: "449.-"},
    {name: "AMD Ryzen 7 5700X3D", socket: "AM4", ram: "DDR4", rating: "64 (C)", cinebench24single: "92", cinebench24multi: "860", cores: "8 (8P)", tdpnormal: "105W", tdpboost: "142W", L3cache: "96MB", price: "249.-"},
    {name: "AMD Ryzen 7 5800X", socket: "AM4", ram: "DDR4", rating: "62 (D)", cinebench24single: "99", cinebench24multi: "890", cores: "8 (8P)", tdpnormal: "105W", tdpboost: "142W", L3cache: "32MB", price: "389.-"},
    {name: "AMD Ryzen 7 5700X", socket: "AM4", ram: "DDR4", rating: "60 (D)", cinebench24single: "95", cinebench24multi: "840", cores: "8 (8P)", tdpnormal: "65W", tdpboost: "88W", L3cache: "32MB", price: "239.-"},
    {name: "AMD Ryzen 5 5600X", socket: "AM4", ram: "DDR4", rating: "52 (D)", cinebench24single: "94", cinebench24multi: "620", cores: "6 (6P)", tdpnormal: "65W", tdpboost: "88W", L3cache: "32MB", price: "219.-"},
    {name: "AMD Ryzen 5 5600", socket: "AM4", ram: "DDR4", rating: "50 (D)", cinebench24single: "92", cinebench24multi: "600", cores: "6 (6P)", tdpnormal: "65W", tdpboost: "88W", L3cache: "32MB", price: "189.-"},
    {name: "AMD Ryzen 5 5500", socket: "AM4", ram: "DDR4", rating: "44 (E)", cinebench24single: "82", cinebench24multi: "530", cores: "6 (6P)", tdpnormal: "65W", tdpboost: "88W", L3cache: "16MB", price: "119.-"}
];

Hier ist deine vollständige, massiv ausgebaute Mainboard-Datenbank als JavaScript-Array. Ich habe exakt die 49 von dir genannten Modelle von ASUS, MSI, Gigabyte und ASRock recherchiert, nach ihren jeweiligen Sockeln sortiert und alle technischen Details wie Chipsatz, Anschlüsse, M.2-Slots und die ungefähren Schweizer UVP-Richtwerte (in CHF) eingetragen.

---

```javascript
// Master-Datenbank für Mainboards (49 Modelle sortiert nach Sockel & Kompatibilität)
const motherboards = [

    // =========================================================================
    // 1. AMD SOCKEL AM5 (Unterstützt Ryzen 7000 / 9000 – Nur DDR5)
    // =========================================================================
    {
        name: "ProArt X870E-Creator WiFi",
        brand: "ASUS",
        chipset: "X870E",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB (Gen 2)",
        fanHeaders: 8,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 1x USB 2.0",
        usbC: "2x USB4 (40Gbps), 1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1, // DP-In für Grafikkarten-Pass-Through
        hdmi: 1,
        specialFeatures: "10G + 2.5G Dual-LAN, Schöpfer-Fokus, PCIe Slot Q-Release Slim, Wifi 7",
        price: "499.-"
    },
    {
        name: "X870E Aorus Master",
        brand: "Gigabyte",
        chipset: "X870E",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "2x USB4 (40Gbps), 1x USB 10Gbps",
        displayPort: 0,
        hdmi: 1,
        specialFeatures: "EZ-Latch Click (Werkzeuglose M.2 & GPU Montage), Wifi 7, massive VRM-Kühlung",
        price: "449.-"
    },
    {
        name: "MPG X870E Carbon WiFi",
        brand: "MSI",
        chipset: "X870E",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "9x USB 10Gbps",
        usbC: "2x USB4 (40Gbps), 1x USB 40Gbps, 1x USB 10Gbps",
        displayPort: 0,
        hdmi: 1,
        specialFeatures: "EZ PCIe Release, 5G + 2.5G Dual-LAN, Mystic Light RGB, Wifi 7",
        price: "459.-"
    },
    {
        name: "X670E Taichi Lite",
        brand: "ASRock",
        chipset: "X670E",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 4,
        sataPorts: 8,
        usbA: "5x USB 10Gbps, 3x USB 5Gbps, 4x USB 2.0",
        usbC: "2x USB4 (40Gbps)",
        displayPort: 0,
        hdmi: 1,
        specialFeatures: "E-ATX Formfaktor, 24-Phasen-VRM, kostengünstige High-End-Plattform",
        price: "329.-"
    },
    {
        name: "ROG Strix B650E-E Gaming WiFi",
        brand: "ASUS",
        chipset: "B650E",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 4x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 10Gbps (DisplayPort), 1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "PCIe 5.0 auf Grafikkarte und M.2, Diagnostic-Code-Display, Q-Release",
        price: "329.-"
    },
    {
        name: "TUF Gaming B650-Plus WiFi",
        brand: "ASUS",
        chipset: "B650",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Militärstandard-Zertifizierung, extrem beliebter Allrounder",
        price: "199.-"
    },
    {
        name: "MAG B650 Tomahawk WiFi",
        brand: "MSI",
        chipset: "B650",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 3,
        sataPorts: 6,
        usbA: "4x USB 10Gbps, 2x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Pre-installed I/O Shield, massive VRM-Kühlkörper, extrem stabil",
        price: "219.-"
    },
    {
        name: "PRO B650-P WiFi",
        brand: "MSI",
        chipset: "B650",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 2,
        sataPorts: 6,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Dezentes Industrie-Design ohne RGB am Board, starkes P/L-Verhältnis",
        price: "179.-"
    },
    {
        name: "B650 Aorus Elite AX",
        brand: "Gigabyte",
        chipset: "B650",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 5,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "2x USB 10Gbps, 5x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Twin-Digital-VRM-Design, EZ-Latch für schnelle SSD-Montage",
        price: "229.-"
    },
    {
        name: "B650 Eagle AX",
        brand: "Gigabyte",
        chipset: "B650",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 5,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "1x USB 10Gbps, 3x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 5Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Budget-Einstiegs-ATX-Board für AM5 mit solidem Feature-Set",
        price: "159.-"
    },
    {
        name: "B650M PG Riptide WiFi",
        brand: "ASRock",
        chipset: "B650",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 5,
        m2Slots: 2,
        sataPorts: 4,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Kompakter Micro-ATX Formfaktor, Phantom Gaming Design",
        price: "169.-"
    },
    {
        name: "B650 Pro RS",
        brand: "ASRock",
        chipset: "B650",
        socket: "AM5",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 6x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Silber-weisses Design-Thema, exzellenter Preis für 3x M.2 Slots",
        price: "189.-"
    },

    // =========================================================================
    // 2. INTEL SOCKEL LGA1851 (Unterstützt Core Ultra 200 – Nur DDR5)
    // =========================================================================
    {
        name: "ROG Maximus Z890 Hero",
        brand: "ASUS",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB (Gen 2)",
        fanHeaders: 8,
        m2Slots: 6,
        sataPorts: 4,
        usbA: "4x USB 10Gbps",
        usbC: "2x Thunderbolt 4 (40Gbps), 1x USB 20Gbps, 2x USB 10Gbps",
        displayPort: 0, 
        hdmi: 1,
        specialFeatures: "Polymo Lighting II Matrix-Display auf I/O-Cover, LiveDash Diagnostic-Display, Wifi 7",
        price: "689.-"
    },
    {
        name: "ROG Strix Z890-E Gaming WiFi",
        brand: "ASUS",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB",
        fanHeaders: 7,
        m2Slots: 7, // Rekordverdächtige Anzahl an M.2 Slots
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 3x USB 5Gbps",
        usbC: "2x Thunderbolt 4 (40Gbps), 1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Start-Knopf direkt auf dem Board, Q-Release Slim, massiver VRM-Kühler",
        price: "529.-"
    },
    {
        name: "TUF Gaming Z890-Pro WiFi",
        brand: "ASUS",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB",
        fanHeaders: 7,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 2x USB 5Gbps",
        usbC: "1x Thunderbolt 4 (40Gbps), 1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Robuste TUF-Bauteile, Wifi 7, sehr faires Z890-Einsteigerpaket",
        price: "319.-"
    },
    {
        name: "MAG Z890 Tomahawk WiFi",
        brand: "MSI",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 4x USB 5Gbps",
        usbC: "2x Thunderbolt 4 (40Gbps), 1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Ultra-schnelles Intel Killer 5G LAN, EZ M.2 Clips für werkzeugfreie Montage",
        price: "329.-"
    },
    {
        name: "PRO Z890-A WiFi",
        brand: "MSI",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps",
        usbC: "1x Thunderbolt 4 (40Gbps), 1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Silberne Akzente, optimiert für professionelle Workstations und cleanes Gaming",
        price: "269.-"
    },
    {
        name: "Z890 Aorus Master",
        brand: "Gigabyte",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 5,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 4x USB 5Gbps",
        usbC: "2x Thunderbolt 4 (40Gbps), 1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "10G Super-LAN + Wifi 7, EZ-Latch Click für GPU, audiophile Kondensatoren",
        price: "499.-"
    },
    {
        name: "Z890 Aorus Elite WiFi7",
        brand: "Gigabyte",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 20Gbps, 1x USB 10Gbps (Unterstützt DP)",
        displayPort: 0,
        hdmi: 1,
        specialFeatures: "Wifi 7 mit magnetischer Richtantenne, sehr gutes VRM-Kühldesign",
        price: "289.-"
    },
    {
        name: "Z890 Taichi Lite",
        brand: "ASRock",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 6,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 4x USB 5Gbps",
        usbC: "2x Thunderbolt 4 (40Gbps), 1x USB 20Gbps",
        displayPort: 0,
        hdmi: 1,
        specialFeatures: "Gleiche brachiale VRM-Power wie das teure Taichi, aber reduziertes RGB-Layout",
        price: "399.-"
    },
    {
        name: "Z890 Pro RS",
        brand: "ASRock",
        chipset: "Z890",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 4,
        sataPorts: 4,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Mattschwarzes Design, günstiges Z-Board für reines CPU-Overclocking",
        price: "229.-"
    },
    {
        name: "TUF Gaming B860-PLUS WiFi",
        brand: "ASUS",
        chipset: "B860",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB",
        fanHeaders: 6,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps",
        usbC: "1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Der B-Chipsatz-Favorit für Core Ultra 5 / 7 Setups ohne manuelles OC",
        price: "199.-"
    },
    {
        name: "MAG B860M Mortar WiFi",
        brand: "MSI",
        chipset: "B860",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 5,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "3x USB 10Gbps, 4x USB 2.0",
        usbC: "1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Kompaktes Micro-ATX Kraftpaket, ideal für kleinere Gaming-Cases",
        price: "189.-"
    },
    {
        name: "B860 Aorus Elite",
        brand: "Gigabyte",
        chipset: "B860",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 5,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "3x USB 10Gbps, 4x USB 5Gbps",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Stylisches Mainstream-Board mit exzellenten RAM-OC Profilen",
        price: "189.-"
    },
    {
        name: "B860 Steel Legend WiFi",
        brand: "ASRock",
        chipset: "B860",
        socket: "1851",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Camo-Schnee-Optik, sehr dicke Kühler für langanhaltende Gaming-Sessions",
        price: "179.-"
    },

    // =========================================================================
    // 3. INTEL SOCKEL LGA1700 (12. / 13. / 14. Gen – Standardmässig DDR5)
    // =========================================================================
    {
        name: "ROG Strix Z790-F Gaming WiFi II",
        brand: "ASUS",
        chipset: "Z790",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 5,
        sataPorts: 4,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 20Gbps (Mit 30W Fast-Charge Support), 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Q-Release Taste für massiv vereinfachten Grafikkarten-Ausbau, Wifi 7",
        price: "379.-"
    },
    {
        name: "MPG Z790 Carbon WiFi",
        brand: "MSI",
        chipset: "Z790",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 5,
        sataPorts: 6,
        usbA: "4x USB 10Gbps, 4x USB 5Gbps",
        usbC: "1x USB 20Gbps, 1x USB 10Gbps (Mit DisplayPort)",
        displayPort: 0,
        hdmi: 1,
        specialFeatures: "Carbon-Carbon-Look, POST-Code LED-Anzeige für Fehlercodes",
        price: "429.-"
    },
    {
        name: "PRO Z790-A MAX WiFi",
        brand: "MSI",
        chipset: "Z790",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 4,
        sataPorts: 8,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 20Gbps, 1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "MAX-Version mit nativem Wi-Fi 7 und optimierten Signalwegen für hohen RAM-Takt",
        price: "259.-"
    },
    {
        name: "Z790 Aorus Elite AX",
        brand: "Gigabyte",
        chipset: "Z790",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 4,
        sataPorts: 6,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Fortschrittliche thermische Abdeckung über allen M.2 Slots",
        price: "269.-"
    },
    {
        name: "Prime Z790-P WiFi",
        brand: "ASUS",
        chipset: "Z790",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 5,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Klassisch silber-weisses Design, fokussiert auf Kernfunktionen",
        price: "219.-"
    },
    {
        name: "Z790 Gaming X AX",
        brand: "Gigabyte",
        chipset: "Z790",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 4,
        sataPorts: 6,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 5x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Kostengünstiges ATX-Z790 Board mit starker Spannungsversorgung",
        price: "219.-"
    },
    {
        name: "Z790 Pro RS",
        brand: "ASRock",
        chipset: "Z790",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 4,
        sataPorts: 8,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Sehr viele SATA-Anschlüsse (8 Stück) für Speicher-Liebhaber",
        price: "209.-"
    },
    {
        name: "Z790 Riptide WiFi",
        brand: "ASRock",
        chipset: "Z790",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 5,
        sataPorts: 8,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Killer 2.5G Gaming LAN, extremes VRM-Layout in dieser Preisklasse",
        price: "249.-"
    },
    {
        name: "TUF Gaming B760-Plus WiFi",
        brand: "ASUS",
        chipset: "B760",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 3x USB 2.0",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Hervorragende Allround-Plattform für Intel Core i5 Non-K Prozessoren",
        price: "189.-"
    },
    {
        name: "MAG B760 Tomahawk WiFi",
        brand: "MSI",
        chipset: "B760",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "4x USB 10Gbps, 4x USB 2.0",
        usbC: "1x USB 20Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Exzellente passive Kühlblöcke für M.2 SSDs, schlichtes schwarzes Design",
        price: "209.-"
    },
    {
        name: "B760 Gaming X AX",
        brand: "Gigabyte",
        chipset: "B760",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 5x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Sehr günstiger Einstieg in den LGA1700-Bereich mit DDR5-Support",
        price: "169.-"
    },
    {
        name: "B760M Steel Legend WiFi",
        brand: "ASRock",
        chipset: "B760",
        socket: "LGA1700",
        socketCount: 1,
        ramType: "DDR5",
        ramSlots: 4,
        rgbHeaders: "3x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 5,
        m2Slots: 3,
        sataPorts: 4,
        usbA: "1x USB 10Gbps, 4x USB 5Gbps",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Kompaktes mATX-Board mit extrem edler weiss-silberner Steel Legend Ästhetik",
        price: "179.-"
    },

    // =========================================================================
    // 4. AMD SOCKEL AM4 (Unterstützt Ryzen 5000er Serie – Nur DDR4)
    // =========================================================================
    {
        name: "ROG Crosshair VIII Dark Hero",
        brand: "ASUS",
        chipset: "X570",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 2,
        sataPorts: 8,
        usbA: "7x USB 10Gbps, 4x USB 5Gbps",
        usbC: "1x USB 10Gbps",
        displayPort: 0,
        hdmi: 0, // Reine Enthusiasten-Karte, benötigt zwingend dedizierte GPU
        specialFeatures: "Legendärer passiver Chipsatzkühler (lautlos), Dynamic OC Switcher",
        price: "439.-"
    },
    {
        name: "X570S Aorus Master",
        brand: "Gigabyte",
        chipset: "X570S",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 4,
        sataPorts: 6,
        usbA: "4x USB 10Gbps, 2x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 0,
        hdmi: 0,
        specialFeatures: "Überarbeitete lüfterlose X570S-Version, ESS SABRE HiFi Audio-Chip",
        price: "349.-"
    },
    {
        name: "MPG X570S Carbon Max WiFi",
        brand: "MSI",
        chipset: "X570S",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 4,
        sataPorts: 8,
        usbA: "3x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 0,
        hdmi: 1,
        specialFeatures: "Massives M.2 Shield Frozr Kühlsystem für alle 4 SSD-Steckplätze",
        price: "289.-"
    },
    {
        name: "X570 Taichi",
        brand: "ASRock",
        chipset: "X570",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "1x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 3,
        sataPorts: 8,
        usbA: "1x USB 10Gbps, 6x USB 5Gbps",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Zahnrad-Design-Thema mit RGB-Beleuchtung, integrierter Flex-Heatpipe-Kühler",
        price: "329.-"
    },
    {
        name: "ROG Strix B550-F Gaming WiFi",
        brand: "ASUS",
        chipset: "B550",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "1x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 2,
        sataPorts: 6,
        usbA: "2x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Intel 2.5G Ethernet, Cyberpunk-Design-Akzente, Spitzen-Audio (SupremeFX)",
        price: "189.-"
    },
    {
        name: "TUF Gaming B550-Plus",
        brand: "ASUS",
        chipset: "B550",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "1x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 6,
        m2Slots: 2,
        sataPorts: 6,
        usbA: "1x USB 10Gbps, 4x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Solide Digi+ VRM Spannungsversorgung, langlebige Militär-Kondensatoren",
        price: "149.-"
    },
    {
        name: "MAG B550 Tomahawk",
        brand: "MSI",
        chipset: "B550",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 2,
        sataPorts: 6,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 2x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Dual-LAN (2.5G + 1G), extrem starke Kühlkörper auf den VRMs",
        price: "159.-"
    },
    {
        name: "B550-A Pro",
        brand: "MSI",
        chipset: "B550",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "1x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 8,
        m2Slots: 2,
        sataPorts: 6,
        usbA: "1x USB 10Gbps, 2x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Schlichtes braun-schwarzes Design, ideal für schlichte Arbeits- & Gaming-PCs",
        price: "119.-"
    },
    {
        name: "B550 Aorus Elite V2",
        brand: "Gigabyte",
        chipset: "B550",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 5,
        m2Slots: 2,
        sataPorts: 4,
        usbA: "2x USB 10Gbps, 3x USB 5Gbps, 2x USB 2.0",
        usbC: "Keine am I/O-Panel (Nur interner Header)",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Integrierte I/O-Blende, sehr gute RAM-Kompatibilität",
        price: "139.-"
    },
    {
        name: "B550M DS3H",
        brand: "Gigabyte",
        chipset: "B550",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "1x 3-Pin ARGB, 1x 4-Pin RGB",
        fanHeaders: 3,
        m2Slots: 2,
        sataPorts: 4,
        usbA: "4x USB 5Gbps, 4x USB 2.0",
        usbC: "Keine",
        displayPort: 0,
        hdmi: 1,
        specialFeatures: "Super kompaktes Micro-ATX Budgetboard, der absolute Preisschlager",
        price: "89.-"
    },
    {
        name: "B550 Pro4",
        brand: "ASRock",
        chipset: "B550",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 2,
        sataPorts: 6,
        usbA: "1x USB 10Gbps, 4x USB 5Gbps",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Umfangreiche Lüftersteuerung, Post Status Checker LEDs integriert",
        price: "115.-"
    },
    {
        name: "B550 Steel Legend",
        brand: "ASRock",
        chipset: "B550",
        socket: "AM4",
        socketCount: 1,
        ramType: "DDR4",
        ramSlots: 4,
        rgbHeaders: "2x 3-Pin ARGB, 2x 4-Pin RGB",
        fanHeaders: 7,
        m2Slots: 2,
        sataPorts: 6,
        usbA: "1x USB 10Gbps, 1x USB 5Gbps, 4x USB 2.0",
        usbC: "1x USB 10Gbps",
        displayPort: 1,
        hdmi: 1,
        specialFeatures: "Brillante On-Board RGB-Zonen, extrem dicke Dr.MOS MOSFET-Kühlung",
        price: "159.-"
    }
];

```

